#!/bin/bash

set -u                          # Treat unset variables as an error
set -e #  Exit immediately if a simple command exits with a non-zero status

ABSOLUTE_PATH=$(readlink -f $0)
HOME="${ABSOLUTE_PATH%/*/*}"
DB_NAME='rssminer'
DB_USER='feng'
BACKUP_FOLDER="/var/rssminer_backup"

log() {
    echo "`date --rfc-3339=seconds` INFO -- $@"
}

error() {
    echo "`date --rfc-3339=seconds` ERROR -- $@"
}

drop_db() {
    SQL="drop database if exists $1"
    log $SQL
    mysql -uroot -e "$SQL"
}

create_db() {
    SQL="create database $1"
    log $SQL
    mysql -uroot -e "$SQL"
}

# GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%';
# CREATE USER admin@'%' IDENTIFIED BY ''

recreate_db_and_user () {
    drop_db $DB_NAME
    create_db $DB_NAME
    mysql -uroot mysql -e "DROP USER '$DB_USER'@localhost"
    mysql -uroot -e "CREATE USER '$DB_USER'@'localhost' IDENTIFIED BY ''";
    mysql -uroot -e "GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'localhost';"
}

init_db() {
    recreate_db_and_user
    mysql -u$DB_USER $DB_NAME < $HOME/src/rssminer.sql
}

backup_db() {
    if [ ! -d $BACKUP_FOLDER ]; then
        sudo mkdir -p $BACKUP_FOLDER
        sudo chown -R feng:feng $BACKUP_FOLDER
    fi
    D=`date +"%Y%m%d%H%M"`
    BACKUP_SQL="$BACKUP_FOLDER/rssminer_$D.sql.gz"
    log "Back up to file $BACKUP_SQL"
    ssh rssminer.net "mysqldump -u $DB_USER --routines --single-transaction --database $DB_NAME --add-drop-database --add-drop-table | gzip --stdout" > $BACKUP_SQL
}

restore_db () {
    recreate_db_and_user
    FILE=`ls $BACKUP_FOLDER -t |head -1`
    FILE="$BACKUP_FOLDER/$FILE"
    if [ -f "$FILE" ]; then
        log "restore $DB_NAME db from file $FILE"
        zcat $FILE | mysql -ufeng
        # mysql -ufeng < $file
    else
        error "Backup sql file is required"
    fi
}

# online version
# ssh deploy@rssminer.net 'sudo /etc/init.d/rssminer rebuild-index'

rebuild_index () {
    log "rm -rf /var/rssminer/index/*"
    rm -rf /var/rssminer/index/*
    cd "${HOME}" && java \
        -Dfile.encoding=UTF-8 \
        -Dsun.jnu.encoding=UTF-8 \
        -Xms150m -Xmx150m \
        -server -cp "classes:lib/*:src/" clojure.main \
        -m rssminer.admin -c rebuild-index
}

usage () {
    cat <<-EOF
USAGE:
admin [options] [command]

Options:
  -d --db-name       mysql database name
  -u --db-user-name  mysql username to create

Commands:
  init-db            initialize database, create user, import schema
  backup-db          backup mysql database from online
  restore-db         restore backuped mysql database
  rebuild-index      rebuild luence index
EOF
}

while test $# -ne 0; do
    arg=$1; shift
    case $arg in
        -h|--help) usage; exit;;
        -d|--db-name) DB_NAME=$1; shift;;
        -u|--db-user-name) DB_USER=$1; shift;;
        init-db) init_db $@; exit;;
        backup-db) backup_db; exit;;
        restore-db) restore_db $@; exit;;
        rebuild-index) rebuild_index $@; exit;;
        *) usage; exit;;
    esac
done

# reach hear, no args is given
usage

# ssh server 'mysqldump -u feng --routines --single-transaction --database user0 --add-drop-database --add-drop-table | gzip --stdout' | zcat > /tmp/backup_user0.sql

# clear root password
# update mysql.user set password=null where user='root';

# 1 3 * * *   wget --header "Cookie:_id_={{id}}" http://127.0.0.1:8100/admin/compute > /tmp/compute.log
# auto start on server reboot
# sudo update-rc.d rssminer defaults;
