#!/bin/bash

set -u                          # Treat unset variables as an error
set -e #  Exit immediately if a simple command exits with a non-zero status

READLINK=readlink
if which greadlink > /dev/null; then
    READLINK=greadlink
fi

ABSOLUTE_PATH=$(${READLINK} -f $0)
HOME="${ABSOLUTE_PATH%/*/*}"
DB_NAME='rssminer'
DB_USER='feng'
BACKUP_FOLDER="/var/rssminer_backup"
DB_HOST='127.0.0.1'
MYSQL="mysql --host $DB_HOST -uroot"

log() {
    echo "`date "+%Y-%m-%d %H:%M:%S"` INFO -- $@"
    # echo "`date --rfc-3339=seconds` INFO -- $@"
}

error() {
    echo "`date "+%Y-%m-%d %H:%M:%S"` ERROR -- $@"
}

drop_db() {
    SQL="drop database if exists $1"
    log $SQL
    $MYSQL -e "$SQL"
}

create_db() {
    SQL="create database $1"
    log $SQL
    $MYSQL -e "$SQL"
}

# CREATE USER feng@'%' IDENTIFIED BY ''
# GRANT ALL PRIVILEGES ON *.* TO 'feng'@'%' with grant option;
# flush privileges

recreate_db_and_user () {
    drop_db $DB_NAME
    create_db $DB_NAME
    # otherwise drop user may fail
    $MYSQL -e "GRANT USAGE ON *.* TO '$DB_USER'@'localhost';"
    $MYSQL mysql -e "DROP USER '$DB_USER'@localhost"
    $MYSQL -e "CREATE USER '$DB_USER'@'localhost' IDENTIFIED BY ''";
    $MYSQL -e "GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'localhost';"
}

init_db() {
    recreate_db_and_user
    $MYSQL $DB_NAME < $HOME/scripts/rssminer.sql
}

backup_db() {
    if [ ! -d $BACKUP_FOLDER ]; then
        sudo mkdir -p $BACKUP_FOLDER
        sudo chown -R feng:feng $BACKUP_FOLDER
    fi
    D=`date +"%Y%m%d%H%M"`
    BACKUP_SQL="$BACKUP_FOLDER/rssminer_$D.sql.gz"
    log "Back up to file $BACKUP_SQL"
    ssh rssminer.net "mysqldump -u $DB_USER --routines --single-transaction --database $DB_NAME --ignore-table=rssminer.feed_data --ignore-table=rssminer.favicon --add-drop-database --add-drop-table | gzip --stdout" > $BACKUP_SQL
}

backup_summary() {
    if [ ! -d $BACKUP_FOLDER ]; then
        sudo mkdir -p $BACKUP_FOLDER
        sudo chown -R feng:feng $BACKUP_FOLDER
    fi
    D=`date +"%Y%m%d%H%M"`
    BACKUP_SQL="$BACKUP_FOLDER/feed_data_$D.sql.gz"
    log "Back up feed_data to file $BACKUP_SQL"
    ssh rssminer.net "mysqldump -u $DB_USER $DB_NAME feed_data | gzip --stdout" > $BACKUP_SQL
}

restore_db () {
    recreate_db_and_user
    # abs path already
    FILE=`ls $BACKUP_FOLDER/rssminer* -t |head -1`
    # FILE="$BACKUP_FOLDER/$FILE"
    if [ -f "$FILE" ]; then
        log "restore $DB_NAME db from file $FILE"
        zcat $FILE | $MYSQL
    else
        error "Backup sql file is required"
    fi

    FILE="$BACKUP_FOLDER/favicon.sql"
    if [ -f "$FILE" ]; then
        log "restore favicon from file $FILE"
        cat $FILE | $MYSQL $DB_NAME
    fi

    FILE=`ls $BACKUP_FOLDER/feed_data* -t |head -1`
    # FILE="$BACKUP_FOLDER/$FILE"
    if [ -f "$FILE" ]; then
        log "restore feed_data from file $FILE"
        zcat $FILE | $MYSQL $DB_NAME
    else
        cat $HOME/scripts/missing.sql | $MYSQL $DB_NAME
        error "feed_data is not restored"
    fi
}

# online version
# ssh deploy@rssminer.net 'sudo /etc/init.d/rssminer rebuild-index'

rebuild_index () {
    log "rm -rf /var/rssminer/index/*"
    rm -rf /var/rssminer/index/*
    cd "${HOME}" && java \
        -Dfile.encoding=UTF-8 \
        -Dsun.jnu.encoding=UTF-8 \
        -Xms88m -Xmx88m -XX:PermSize=32M -XX:MaxPermSize=32M \
        -server -cp "classes:lib/*:src/" clojure.main \
        -m rssminer.admin -c rebuild-index
}

usage () {
    cat <<-EOF
USAGE:
admin [options] [command]

Options:
  -d --db-name       mysql database name
  -u --db-user-name  mysql username to create

Commands:
  init-db            initialize database, create user, import schema
  backup-db          backup mysql database from online
  restore-db         restore backuped mysql database
  rebuild-index      rebuild luence index
  backup-summary     backup feed summary table
EOF
}

while test $# -ne 0; do
    arg=$1; shift
    case $arg in
        -h|--help) usage; exit;;
        -d|--db-name) DB_NAME=$1; shift;;
        -u|--db-user-name) DB_USER=$1; shift;;
        init-db) init_db $@; exit;;
        backup-db) backup_db; exit;;
        restore-db) restore_db $@; exit;;
        rebuild-index) rebuild_index $@; exit;;
        backup-summary) backup_summary $@; exit;;
        *) usage; exit;;
    esac
done

# reach hear, no args is given
usage

# ssh server 'mysqldump -u feng --routines --single-transaction --database user0 --add-drop-database --add-drop-table | gzip --stdout' | zcat > /tmp/backup_user0.sql

# clear root password
# update mysql.user set password=null where user='root';

# schedule refetch
# update rss_links set next_check_ts =  FLOOR(1 + RAND() * 7200) where total_feeds = 0;

# recompute for all uses in the morning
# 1 3 * * *   wget --header "Cookie:_id_={{id}}" http://127.0.0.1:8100/admin/compute > /tmp/compute.log

# auto start on server reboot
# sudo update-rc.d rssminer defaults;
