#! /bin/bash -x

TARGET_DIR=/tmp/rssminer_tmp
rm -rf $TARGET_DIR
cp -r /home/feng/workspace/rssminer $TARGET_DIR

cd $TARGET_DIR
rm classes -r
lein compile
cp src/templates classes -r
rm classes/templates/tmpls/ -r
cd classes
jar -cf ../rssminer.jar *
cd $TARGET_DIR
rake prepare_prod

java -Dsun.jnu.encoding=UTF-8 \
    -Dfile.encoding=UTF-8 \
    -Dsun.net.inetaddr.ttl=0 \
    -Djava.net.preferIPv4Stack=true \
    -Xmx256m -Xms256m \
    -cp rssminer.jar:lib/* rssminer.main \
    --index-path /var/rssminer/index \
    --profile prod \
    --worker 4 \
    --port 9090 \
