#!/bin/bash -x

set -e

ABSOLUTE_PATH=$(readlink -f $0)
RSSMINER_CODE_ROOT="${ABSOLUTE_PATH%/*/*}"

rm bin classes -rf && lein compile
cp src/templates classes -r
rm classes/templates/tmpls/ -r
cd classes
jar -cf ../rssminer.jar *
cd $RSSMINER_CODE_ROOT

# FRONTEND_HOST="192.168.1.117"
FRONTEND_HOST=rssminer.net
DEPLOYMENT_USER="deploy"
SSH_TARGET="${DEPLOYMENT_USER}@${FRONTEND_HOST}"
TARGET_DIR="/var/www/rssminer"
DATA_ROOT="/var/rssminer"

function remote_run {
    ssh "${SSH_TARGET}" "$1"
}

# Create the directory if this is the first deployment.
remote_run "sudo mkdir -p ${TARGET_DIR} && sudo chown deploy ${TARGET_DIR}"
remote_run "sudo mkdir -p ${DATA_ROOT} && sudo chown deploy ${DATA_ROOT}"
rsync --rsh='ssh' -vr --delete --delete-excluded \
    --exclude-from conf/exclude.txt \
    "${RSSMINER_CODE_ROOT}/" "${SSH_TARGET}:${TARGET_DIR}/"

remote_run "sudo cp ${TARGET_DIR}/scripts/rssminer /etc/init.d/"
remote_run "sudo chmod +x /etc/init.d/rssminer"
remote_run "sudo /etc/init.d/rssminer restart"

remote_run "sudo cp ${TARGET_DIR}/conf/nginx/rssminer /etc/nginx/sites-available"
remote_run "sudo cp ${TARGET_DIR}/conf/nginx/gzip.conf /etc/nginx/conf.d"
remote_run "cd /etc/nginx/sites-enabled  && sudo ln -f -s /etc/nginx/sites-available/rssminer"
remote_run "sudo service nginx restart"

rm rssminer.jar
exit 0

