#!/bin/bash

set -e

READLINK=readlink
FRONTEND_HOST="rssminer.net"
ABSOLUTE_PATH=$(${READLINK} -f $0)
RSSMINER_HOME="${ABSOLUTE_PATH%/*/*}"
DEPLOYMENT_USER="deploy"
SSH_TARGET="${DEPLOYMENT_USER}@${FRONTEND_HOST}"
TARGET_DIR="/var/www/rssminer"

function remote_run {
    ssh "${SSH_TARGET}" "$1"
}
# Create the directory if this is the first deployment.
remote_run "sudo mkdir -p ${TARGET_DIR} && sudo chown deploy ${TARGET_DIR}"

rm classes -rf && lein javac

rsync --rsh='ssh' -vr --delete --delete-excluded \
    --exclude-from conf/exclude.txt \
    "${RSSMINER_HOME}/" "${SSH_TARGET}:${TARGET_DIR}/"

remote_run "sudo cp ${TARGET_DIR}/conf/rssminer.conf /etc/init/"
remote_run "sudo cp ${TARGET_DIR}/conf/nginx/rssminer /etc/nginx/sites-available"
remote_run "sudo cp ${TARGET_DIR}/conf/nginx/gzip.conf /etc/nginx/conf.d"
remote_run "cd /etc/nginx/sites-enabled  && sudo ln -f -s /etc/nginx/sites-available/rssminer"

remote_run "sudo restart rssminer || sudo start rssminer"
remote_run "sudo service nginx restart"
