#!/bin/bash -x

set -u                          # Treat unset variables as an error
set -e #  Exit immediately if a simple command exits with a non-zero status

READLINK=readlink
if which greadlink > /dev/null; then
    READLINK=greadlink
fi

ABSOLUTE_PATH=$(${READLINK} -f $0)
RSSMINER_CODE_ROOT="${ABSOLUTE_PATH%/*/*}"

# rm bin classes -rf && lein compile
# cp src/templates classes -r
# cp src/logback.xml classes/logback.xml
# cp src/words.dic classes/words.dic
# rm classes/templates/tmpls/ -r
# cd classes
# jar -cf ../rssminer.jar *
cd $RSSMINER_CODE_ROOT
./scripts/gen_icon
./scripts/javac
export LEIN_SNAPSHOTS_IN_RELEASE=true
lein uberjar

mv target/rssminer-standalone.jar .

# FRONTEND_HOST="192.168.1.117"
FRONTEND_HOST=rssminer.net
DEPLOYMENT_USER=deploy
SSH_TARGET="${DEPLOYMENT_USER}@${FRONTEND_HOST}"
TARGET_DIR="/var/www/rssminer"
DATA_ROOT="/var/rssminer"

function remote_run {
    ssh "${SSH_TARGET}" "$1"
}

# Create the directory if this is the first deployment.
remote_run "sudo mkdir -p ${TARGET_DIR} && sudo chown deploy ${TARGET_DIR}"
remote_run "sudo mkdir -p ${DATA_ROOT} && sudo chown deploy ${DATA_ROOT}"
rsync --rsh='ssh' -vr --delete --delete-excluded \
    --exclude-from conf/exclude.txt \
    "${RSSMINER_CODE_ROOT}/" "${SSH_TARGET}:${TARGET_DIR}/"

# remote_run "sudo cp ${TARGET_DIR}/scripts/rssminer /etc/init.d/"
# remote_run "sudo chmod +x /etc/init.d/rssminer"
# remote_run "sudo /etc/init.d/rssminer restart"

# remote_run "sudo cp ${TARGET_DIR}/conf/nginx/rssminer /etc/nginx/sites-available"
# remote_run "sudo cp ${TARGET_DIR}/conf/nginx/gzip.conf /etc/nginx/conf.d"
# remote_run "cd /etc/nginx/sites-enabled  && sudo ln -f -s /etc/nginx/sites-available/rssminer"
# remote_run "sudo service nginx reload"

remote_run "cd ${TARGET_DIR} && ./scripts/remote_run"

# rm .jar
# exit 0
