#!/bin/sh

ABSOLUTE_PATH=$(readlink -f $0)
RSSMINER_HOME="${ABSOLUTE_PATH%/*/*}"

SCRIPT_FILE=h2
VERSION=1.3.163

CP=$RSSMINER_HOME/lib/h2-${VERSION}.jar
SHELL=org.h2.tools.Shell
SERVER=org.h2.tools.Server
SCRIPT=org.h2.tools.Script
RUNSCRIPT=org.h2.tools.RunScript
DB_PATH=/var/rssminer/rssminer

case "$1" in
    backup)
        if [ $# = 2 ]
        then
            DEST=$2
        elif [ $# = 3 ]
        then
            DB_PATH=$2
            DEST=$3
        else
            echo "h2 backup [$DB_PATH] dest-path"
            exit 0
        fi
        java -cp $CP $SCRIPT \
            -url "jdbc:h2:$DB_PATH;AUTO_SERVER=TRUE;MVCC=true" \
            -user sa \
            -script $DEST \
            -options compression zip
        ;;
    restore)
        if [ $# = 3 ]
        then
            SRC=$2
            DEST=$3
            java -cp $CP $RUNSCRIPT \
                -url "jdbc:h2:$DEST;FILE_LOCK=FS;MVCC=true" \
                -user sa \
                -script $SRC \
                -options compression zip
        else
            echo "$SCRIPT_FILE restore src dest"
        fi
        ;;
    server)
        java -cp $CP $SERVER -tcp -tcpAllowOthers
        ;;
    shell)
        if [ $# = 2 ]
        then
            # tcp://127.0.0.1//var/rssminer/rssminer
            DB_PATH=$2
        fi
        echo -n "\033]0;h2 console $DB_PATH\007"
        rlwrap java -cp $CP $SHELL \
            -url "jdbc:h2:$DB_PATH;FILE_LOCK=FS;MVCC=true" \
            -user sa
        ;;
    *)
        echo  -e "$SCRIPT_FILE shell \n   backup options \n   restore options \n"
        ;;
esac
exit 0
