#!/bin/bash

rm -f /tmp/h2-1.3.158.jar
cp /home/feng/.m2/repository/com/h2database/h2/1.3.158/h2-1.3.158.jar /tmp

if [ $# != 0 ]
then
    rm -f /tmp/rssminer.trace.db
    rm -f /tmp/rssminer.trace.sql
    cp /dev/shm/rssminer.trace.db /tmp
    cd /tmp && java -cp /tmp/h2-1.3.158.jar org.h2.tools.ConvertTraceFile \
        -traceFile /tmp/rssminer.trace.db \
        -script /tmp/rssminer.trace.sql
else
    rm -f /tmp/rssminer.h2.db
    cp /dev/shm/rssminer.h2.db /tmp
    rlwrap java -cp /tmp/h2-1.3.158.jar org.h2.tools.Shell \
        -url jdbc:h2:/tmp/rssminer -user sa -password sa
fi
