#!/bin/bash

set -u                          # Treat unset variables as an error
set -e #  Exit immediately if a simple command exits with a non-zero status

java -cp `lein classpath` rssminer.TestRunner
