#!/bin/bash

set -u                          # Treat unset variables as an error
set -e #  Exit immediately if a simple command exits with a non-zero status

ABSOLUTE_PATH=$(readlink -f $0)
HOME="${ABSOLUTE_PATH%/*/*}"

cd $HOME

# compile

find test/java -name "*.java" | xargs javac -Xlint:unchecked -cp "classes:lib/*:src/:lib/dev/*"  -d classes -sourcepath test/java

java -cp "lib/*:lib/dev/*:classes/" org.junit.runner.JUnitCore rssminer.TestExtractRssLink
