#!/bin/bash

set -u                          # Treat unset variables as an error
set -e #  Exit immediately if a simple command exits with a non-zero status

APP_HOME=/var/www/rssminer
cd $APP_HOME

INDEX_PATH=/var/rssminer/index
TMP_INDEX_PATH=/var/rssminer/index2

java -server -Dsun.jnu.encoding=UTF-8 \
    -Dfile.encoding=UTF-8 \
    -Dsun.net.inetaddr.ttl=0 \
    -Djava.net.preferIPv4Stack=true \
    -Xms96m -Xmx96m -XX:PermSize=48M -XX:MaxPermSize=48M \
    -cp rssminer-standalone.jar \
    rssminer.admin \
    -c rebuild-index \
    --db-url jdbc:mysql://71.19.154.89/rssminer \
    --index-path $TMP_INDEX_PATH

LOG_DIR=/var/log/rssminer

function running() {
    test -e  $LOG_DIR/master.pid && test -d "/proc/$(cat $LOG_DIR/master.pid)"
}

while running
do
    echo "stop old process"
    cat $LOG_DIR/master.pid | xargs kill
    sleep 1
done

rm $INDEX_PATH -fvr
mv $TMP_INDEX_PATH $INDEX_PATH
ls -lh $INDEX_PATH

./scripts/remote_run
