#!/bin/sh

ABSOLUTE_PATH=$(readlink -f $0)
HOME="${ABSOLUTE_PATH%/*/*}"
cd "${HOME}" && java \
    -Dsun.jnu.encoding=UTF-8 \
    -Dfile.encoding=UTF-8 \
    -Dsun.net.inetaddr.ttl=0 \
    -Djava.net.preferIPv4Stack=true \
    -XX:+UseConcMarkSweepGC \
    -XX:+UseCompressedOops \
    -XX:+UseCompressedStrings \
    -Xms386m -Xmx386m \
    -server -cp "classes:lib/*:src/" clojure.main \
    -m rssminer.main $@

