#!/bin/sh
set -u                          # Treat unset variables as an error
set -e #  Exit immediately if a simple command exits with a non-zero status

READLINK=readlink
if which greadlink > /dev/null; then
    READLINK=greadlink
fi

ABSOLUTE_PATH=$(${READLINK} -f $0)
HOME="${ABSOLUTE_PATH%/*/*}"
cd "${HOME}" && java -server \
    -Xdebug -Xrunjdwp:transport=dt_socket,address=9092,server=y,suspend=n \
    -Dfile.encoding=UTF-8 \
    -Djava.net.preferIPv4Stack=true \
    -Dsun.jnu.encoding=UTF-8 \
    -Dsun.net.inetaddr.ttl=0 \
    -Xms88m -Xmx88m -XX:PermSize=32M -XX:MaxPermSize=32M \
    -server -cp "classes:lib/*:src/" clojure.main \
    -m rssminer.main $@

    # -XX:+UseConcMarkSweepGC \
    # -XX:ParallelGCThreads=2 \
    # -Xdebug -Xrunjdwp:transport=dt_socket,address=9092,server=y,suspend=n \
