#!/bin/sh

# TODO: Move database setup code to Clojure and remove this file.

READLINK=readlink
if which greadlink > /dev/null; then
    READLINK=greadlink
fi

ABSOLUTE_PATH=$(${READLINK} -f $0)
HOME="${ABSOLUTE_PATH%/*/*}"

echo 'DROP DATABASE IF EXISTS feedreader;' | psql -U postgres
echo 'CREATE DATABASE feedreader;' | psql -U postgres
psql -U postgres feedreader -f ${HOME}/src/feedreader.sql
